name: login_rest_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # стейт менеджмент
  flutter_bloc: 8.1.1
  bloc_concurrency: 0.2.0

  # сеть
  dio: 4.0.6
  json_annotation: 4.8.0

  # локализация
  easy_localization: 3.0.2

  # хранение локальных данных
  shared_preferences: 2.0.17
  flutter_secure_storage: ^8.0.0

  # форматированные поля ввода
  mask_text_input_formatter: 2.4.0

  # автоматическое добавление зависимостей
  dep_gen: ^1.0.11

  freezed_annotation: 2.2.0

  auto_route: ^7.7.0

  flutter_keyboard_visibility: ^5.0.3

  get_it: ^7.6.0

  injectable: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # кодогенерация
  build_runner: 2.3.3
  json_serializable: 6.6.0
  freezed: 2.3.2

  # локализация
  easy_localization_loader: 1.0.1+1

  auto_route_generator: ^7.0.0

  injectable_generator: ^2.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/languages/
    - assets/icons/
    - assets/images/

  fonts:
    - family: CustomIcons
      fonts: 
        - asset: assets/icons/icomoon.ttf
